//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeOffice.WpfClient.ExchangeServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExchangeServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExchangeRate", ReplyAction="http://tempuri.org/IService1/GetExchangeRateResponse")]
        string GetExchangeRate(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExchangeRate", ReplyAction="http://tempuri.org/IService1/GetExchangeRateResponse")]
        System.Threading.Tasks.Task<string> GetExchangeRateAsync(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateExchange", ReplyAction="http://tempuri.org/IService1/CalculateExchangeResponse")]
        decimal CalculateExchange(string fromCurrency, string toCurrency, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateExchange", ReplyAction="http://tempuri.org/IService1/CalculateExchangeResponse")]
        System.Threading.Tasks.Task<decimal> CalculateExchangeAsync(string fromCurrency, string toCurrency, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAvailableCurrencies", ReplyAction="http://tempuri.org/IService1/GetAvailableCurrenciesResponse")]
        string GetAvailableCurrencies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAvailableCurrencies", ReplyAction="http://tempuri.org/IService1/GetAvailableCurrenciesResponse")]
        System.Threading.Tasks.Task<string> GetAvailableCurrenciesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        string RegisterUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        System.Threading.Tasks.Task<string> RegisterUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginUser", ReplyAction="http://tempuri.org/IService1/LoginUserResponse")]
        string LoginUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginUser", ReplyAction="http://tempuri.org/IService1/LoginUserResponse")]
        System.Threading.Tasks.Task<string> LoginUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBalance", ReplyAction="http://tempuri.org/IService1/GetBalanceResponse")]
        string GetBalance(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBalance", ReplyAction="http://tempuri.org/IService1/GetBalanceResponse")]
        System.Threading.Tasks.Task<string> GetBalanceAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TopUpAccount", ReplyAction="http://tempuri.org/IService1/TopUpAccountResponse")]
        string TopUpAccount(string username, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TopUpAccount", ReplyAction="http://tempuri.org/IService1/TopUpAccountResponse")]
        System.Threading.Tasks.Task<string> TopUpAccountAsync(string username, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCurrency", ReplyAction="http://tempuri.org/IService1/BuyCurrencyResponse")]
        string BuyCurrency(string username, string currencyCode, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCurrency", ReplyAction="http://tempuri.org/IService1/BuyCurrencyResponse")]
        System.Threading.Tasks.Task<string> BuyCurrencyAsync(string username, string currencyCode, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SellCurrency", ReplyAction="http://tempuri.org/IService1/SellCurrencyResponse")]
        string SellCurrency(string username, string currencyCode, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SellCurrency", ReplyAction="http://tempuri.org/IService1/SellCurrencyResponse")]
        System.Threading.Tasks.Task<string> SellCurrencyAsync(string username, string currencyCode, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTransactionHistory", ReplyAction="http://tempuri.org/IService1/GetTransactionHistoryResponse")]
        string GetTransactionHistory(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTransactionHistory", ReplyAction="http://tempuri.org/IService1/GetTransactionHistoryResponse")]
        System.Threading.Tasks.Task<string> GetTransactionHistoryAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ExchangeOffice.WpfClient.ExchangeServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ExchangeOffice.WpfClient.ExchangeServiceReference.IService1>, ExchangeOffice.WpfClient.ExchangeServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetExchangeRate(string currencyCode) {
            return base.Channel.GetExchangeRate(currencyCode);
        }
        
        public System.Threading.Tasks.Task<string> GetExchangeRateAsync(string currencyCode) {
            return base.Channel.GetExchangeRateAsync(currencyCode);
        }
        
        public decimal CalculateExchange(string fromCurrency, string toCurrency, decimal amount) {
            return base.Channel.CalculateExchange(fromCurrency, toCurrency, amount);
        }
        
        public System.Threading.Tasks.Task<decimal> CalculateExchangeAsync(string fromCurrency, string toCurrency, decimal amount) {
            return base.Channel.CalculateExchangeAsync(fromCurrency, toCurrency, amount);
        }
        
        public string GetAvailableCurrencies() {
            return base.Channel.GetAvailableCurrencies();
        }
        
        public System.Threading.Tasks.Task<string> GetAvailableCurrenciesAsync() {
            return base.Channel.GetAvailableCurrenciesAsync();
        }
        
        public string RegisterUser(string username, string password) {
            return base.Channel.RegisterUser(username, password);
        }
        
        public System.Threading.Tasks.Task<string> RegisterUserAsync(string username, string password) {
            return base.Channel.RegisterUserAsync(username, password);
        }
        
        public string LoginUser(string username, string password) {
            return base.Channel.LoginUser(username, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginUserAsync(string username, string password) {
            return base.Channel.LoginUserAsync(username, password);
        }
        
        public string GetBalance(string username) {
            return base.Channel.GetBalance(username);
        }
        
        public System.Threading.Tasks.Task<string> GetBalanceAsync(string username) {
            return base.Channel.GetBalanceAsync(username);
        }
        
        public string TopUpAccount(string username, decimal amount) {
            return base.Channel.TopUpAccount(username, amount);
        }
        
        public System.Threading.Tasks.Task<string> TopUpAccountAsync(string username, decimal amount) {
            return base.Channel.TopUpAccountAsync(username, amount);
        }
        
        public string BuyCurrency(string username, string currencyCode, decimal amount) {
            return base.Channel.BuyCurrency(username, currencyCode, amount);
        }
        
        public System.Threading.Tasks.Task<string> BuyCurrencyAsync(string username, string currencyCode, decimal amount) {
            return base.Channel.BuyCurrencyAsync(username, currencyCode, amount);
        }
        
        public string SellCurrency(string username, string currencyCode, decimal amount) {
            return base.Channel.SellCurrency(username, currencyCode, amount);
        }
        
        public System.Threading.Tasks.Task<string> SellCurrencyAsync(string username, string currencyCode, decimal amount) {
            return base.Channel.SellCurrencyAsync(username, currencyCode, amount);
        }
        
        public string GetTransactionHistory(string username) {
            return base.Channel.GetTransactionHistory(username);
        }
        
        public System.Threading.Tasks.Task<string> GetTransactionHistoryAsync(string username) {
            return base.Channel.GetTransactionHistoryAsync(username);
        }
    }
}
