//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab2.ConsoleClient.CurrencyServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrencyServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExchangeRate", ReplyAction="http://tempuri.org/IService1/GetExchangeRateResponse")]
        string GetExchangeRate(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExchangeRate", ReplyAction="http://tempuri.org/IService1/GetExchangeRateResponse")]
        System.Threading.Tasks.Task<string> GetExchangeRateAsync(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMultipleRates", ReplyAction="http://tempuri.org/IService1/GetMultipleRatesResponse")]
        string GetMultipleRates(string currencyCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMultipleRates", ReplyAction="http://tempuri.org/IService1/GetMultipleRatesResponse")]
        System.Threading.Tasks.Task<string> GetMultipleRatesAsync(string currencyCodes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Lab2.ConsoleClient.CurrencyServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Lab2.ConsoleClient.CurrencyServiceReference.IService1>, Lab2.ConsoleClient.CurrencyServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetExchangeRate(string currencyCode) {
            return base.Channel.GetExchangeRate(currencyCode);
        }
        
        public System.Threading.Tasks.Task<string> GetExchangeRateAsync(string currencyCode) {
            return base.Channel.GetExchangeRateAsync(currencyCode);
        }
        
        public string GetMultipleRates(string currencyCodes) {
            return base.Channel.GetMultipleRates(currencyCodes);
        }
        
        public System.Threading.Tasks.Task<string> GetMultipleRatesAsync(string currencyCodes) {
            return base.Channel.GetMultipleRatesAsync(currencyCodes);
        }
    }
}
